config/routes.rb
Consonrisas::Application.routes.draw do
  
  resources :contests

  get "/corteo" => "contests#new", :as => :corteo

  resources :need_categories

  get "need/create"

  get "need/destroy"
  
  get "project_need/create"

  get "project_need/destroy"

  resources :news

  get "search/find"

  match '/auth/facebook/logout' => 'application#facebook_logout', :as => :facebook_logout
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  
  resources :authentications

  devise_for :members, :controllers => {:registrations => 'registrations'}
  get "admin/index"
  match 'admin/', :controller => 'admin', :action => 'index'
  match 'admin/db/:table_name.:format', :controller => 'admin', :action => 'get_table_data'  
  match 'admin/db/:table_name/:id', :controller => 'admin', :action => 'update_table_data', :conditions => {:method => :put }  
  match 'admin/db/:table_name', :controller => 'admin', :action => 'create_table_data', :conditions => {:method => :post}
  match 'admin/db/delete/:table_name/:id', :controller => 'admin', :action => 'delete_table_data', :conditions => {:method => :delete }    
  get "admin/members_to_csv" =>"admin#members_to_csv"
  get "admin/fundation_admins_to_csv" =>"admin#fundation_admins_to_csv"  
  get "admin/events_to_csv" =>"admin#events_to_csv"  
  get "admin/fundations_to_csv" =>"admin#fundations_to_csv"  

  
  get "admin/dj_all", :as => :dj_all

  get "admin/dj_show/:id"=> "admin#dj_show"

  get "admin/dj_destroy/:id" => "admin#dj_destroy"
  
  get "admin/workers" => "admin#see_workers"
  
  post "admin/set_workers" => "admin#set_workers"
  

  get "events/gallery"
  
  get "events/all_events"

  post "events/add_facilitator"
  post "events/add_facilitators"  
  post "events/add_fundation"
  post "events/add_fundations"  
  post "events/add_provider"
  post "events/add_providers"  
  post "events/add_show"  
  
  post "events/remove_facilitator"
  post "events/remove_fundation"
  post "events/remove_provider"  
  
  post "fundations/add_follower"
  post "fundations/remove_follower"
  post "fundations/send_msg_to_admins"    
  
  post "providers/add_follower"
  post "providers/remove_follower"
  post "providers/send_msg_to_admins"  
  
  post "facilitators/add_follower"
  post "facilitators/remove_follower"
  post "facilitators/send_msg"
  
  post "fundations/ask_admin"
  post "providers/ask_admin"  
  post "events/ask_admin"  
  
  post "members/respond_fundation_admin"
  post "members/respond_provider_admin"
  post "members/respond_event_admin"    
  match "members/edit_settings"  => "members#edit_settings", :as => :edit_settings
  post "members/delete_alert"      
  get "members/:id/get_fundations" => "members#get_fundations" 
  post "members/check_email" => "members#check_email"
  post "fundations/check_name" => "fundations#check_name"

  root :to => "home#new_index"
  
  get "/info" =>"home#info"

  get "home/new_index"
  get "home/event_comments"
  get "/social" => "home#social"
  get "/mobile" => "home#mobile"
  post "home/feedback"
  
  post "/cleanInitialSession" => "members#cleanInitialSession"
  
  get 'photos/poll'
  

  
  match 'needs/complete/:id' => 'needs#complete'

  get "/facilitators/list" => "facilitators#list"  
 

  
  resources :roles

  resources :members do
    post "update_facebook_id"
    put "change_pic"  
    get "my_invites"
    get "my_msgs"
    post "seen_msgs"
    post "seen_invites"
  end
  post "/members_register" => "members#register"
  post "/accept_invite/:event_id/:role_id" => "members#accept_invite"
  post "/reject_invite/:event_id/:role_id" => "members#reject_invite"  

  resources :populations

  get "/landing" => "home#landing"
  match "project_needs/all_needs", :as => "all_needs"
  match "project_needs/all_needs_landing", :as => "all_needs_landing"  
  get "/soyproyecto" => "home#landing_fundations"
  get "/soyfacilitador" => "home#landing_facilitators"
  get "/soyproveedor" => "home#landing_providers"    
  get "/legal" => "home#legal"

  localized(['es', 'en'], :verbose => true) do
    get "/contact" => "home#contact", :as => :contact
    get "/touch" =>"home#touch", :as => :touch
    get "/donate" =>"home#donate", :as => :donate
    get "/dona" =>"home#donate", :as => :donate
    get "/allies" =>"home#allies",  :as => :allies
    get "/services" => "home#services", :as => :services
    
    resources :events do
      get 'show_gallery'
      resources :photos
      resources :comments
      resources :needs do
          post "complete"
      end
    end  
    resources :facilitators
    resources :providers do
      get "get_pic"
      put "change_pic"
      resources :shows
      resources :contact_informations
    end
    resources :fundations do
      put "change_pic"    
      get "needs"
      resources :contact_informations
      resources :project_needs do
        get 'need'
        post 'help'
      end
         
    end
  end

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  attr_accessible :fundation_id, :fundation_name, :num_tickets, :story, :transport, :video, :email, :pic, :video_html
  belongs_to :fundation

  validates :num_tickets, :numericality => { :less_than_or_equal_to => 15, :greater_than => 0 }, :presence => true

  validates :email, :presence => true

  validates :fundation_id, :presence => true

  has_attached_file :pic, :styles => {:profile_big => "400x400>", :profile => "150x150>", :thumb => "50x50#"},
                    :storage => :s3,
                    :s3_credentials => S3_CREDENTIALS,
                    :path => "contests/:attachment/:id/:style/:filename"
#  process_in_background :pic
#  validates_attachment_presence :pic
  validates_attachment_size :pic, :less_than => 10.megabytes
  validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/
  auto_html_for :video do
    html_escape
    image
    youtube(:width => 400, :height => 250, :autoplay => true)
    vimeo(:width => 400, :height => 250)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contests }
    end
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
    @contest = Contest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contest }
    end
  end

  # GET /contests/new
  # GET /contests/new.json
  def new
    @contest = Contest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contest }
    end
  end

  # GET /contests/1/edit
  def edit
    @contest = Contest.find(params[:id])
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(params[:contest])

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render json: @contest, status: :created, location: @contest }
      else
        format.html { render action: "new" }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contests/1
  # PUT /contests/1.json
  def update
    @contest = Contest.find(params[:id])

    respond_to do |format|
      if @contest.update_attributes(params[:contest])
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest = Contest.find(params[:id])
    @contest.destroy

    respond_to do |format|
      format.html { redirect_to contests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<%= form_for(@contest, :html =>{:multipart=>true}) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2> Este concurso ha terminado, gracias a todos los que participaron, pronto anunciaremos a los ganadores </h2>
  <h1> Pendientes para el próximo concruso!</h1>

  <!-- <div class="field">
    Escoge tu fundación: (Recuerda que debe estar registrada)
    <%= f.select :fundation_id, Fundation.all.collect {|x| [x.name, x.id]}, {:prompt=> "Selecciona Tu Fundación" }%>
    <br/>
    Si no la encuentras, registrala
    <%= link_to "aquí", "/soyproyecto"%>
    para poder participar en concursos de este y otros tipos.
  </div>
  <div class="field">
    ¿Cuántas entradas podrías utilizar?, recuerda que el máximo es 15 incluyendo a los acompañantes y/o adultos responsables.
    <br/>
    <%= f.number_field :num_tickets %>
  </div>
  <div class="field">
    Cuentanos en cuales eventos de nosotros has participado, cuando fue, y qué aprendieron.
    <br/>
    <%= f.text_area :story %>
  </div>
  <div class="field">
    Si tu fundación creó un video, súbelo a youtube.com o a vimeo.com y pega aquí la dirección del video para que nosotros lo podamos ver.<br />
    <%= f.text_field :video %>
  </div>
  <div class="field">
    Si tu fundación creó una pieza gráfica, súbela aquí:
    <br/>
    <%= f.file_field :pic %>
  </div>
  <div class="field">
    Sabemos que conseguir el transporte a veces es complicado, escribe aquí cuanto te costaría el transporte para que nosotros evaluemos si te podemos apoyar.<br />
    <%= f.text_field :transport %>
  </div>
  <div class="field">
    Ingresa un correo en el cual te podamos contactar.<br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit "Participar en este concurso" %>
  </div> -->
<% end %>

app/views/contests/edit.html.erb
<h1>Editing contest</h1>

<%= render 'form' %>
<% if member_signed_in? and current_member.try(:admin?) %>
<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>
<% end %>

app/views/contests/index.html.erb
<h1>Listing contests</h1>
<% if member_signed_in? and current_member.try(:admin?) %>

<table>
  <tr>
    <th>Fundation name</th>
    <th>Num tickets</th>
    <th>Story</th>
    <th>Pic</th>
    <th>Video</th>
    <th>Transport</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contests.each do |contest| %>
  <tr>
    <td><%= Fundation.find(contest.fundation_id).name %></td>
    <td><%= contest.num_tickets %></td>
    <td><%= contest.story %></td>
    <td><%= image_tag contest.pic.url(:thumb) %></td>
    <td><%= contest.video %></td>
    <td><%= contest.transport %></td>
    <td><%= contest.email %></td>
    <td><%= link_to 'Show', contest %></td>
    <td><%= link_to 'Edit', edit_contest_path(contest) %></td>
    <td><%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contest', new_contest_path %>
<% end %>

app/views/contests/new.html.haml
.row
  .span12
    - if @contest.errors.any?
      #error_explanation
        %h2
          = pluralize(@contest.errors.count, "error")
          prohibited this contest from being saved:
        %ul
          - @contest.errors.full_messages.each do |msg|
            %li= msg
.row
  .span12
    %h2  Concurso para ir a ver a Corteo del Circo del sol!
.row
  .span6
    %p
      Tenemos boletas para que tu fundación vaya a ver al Circo del Sol el Miércoles
      %b 18 de Marzo
      del 2015 a las
      %b 7:00 p.m.
    %p
      Son
      %b 30 boletas
      para
      %b 2 fundaciones
      ganadoras del concurso (15 para cada una).
    %p
      %iframe{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/CYQA06f3icU", :width => "560"}
  .span6
    .row
      .span3
        %h3 Concurso:
        %p
          Corteo es una divertida procesión, una cabalgata festiva imaginada por un payaso. El espectáculo une la pasión del actor con la elegancia y el poder del acróbata para zambullir al público asistente en un mundo teatral y misterioso que, situado en algún mágico lugar entre el cielo y la tierra, mezcla diversión, alegría y espontaneidad.
        %p
          Basados en la mezcla de diversión alegría y espontaneidad, queremos invitarte a participar de este concurso.
      .span3
        %p
          =image_tag "corteo.jpg"
.row
  .span12
    %h3 ¿En qué actividades de La liga de las Sonrisas han participado y que han aprendido en estas?

    %p Invitamos a tus beneficiarios (niños, niñas, jóvenes etc) a hacer una pieza gráfica o audiovisual que nos muestre en que actividad de nosotros han participado (puede ser cualquiera de nuestros programas: Conectando Sonrisas, Magos Sin Fronteras, Laboratorio con Sonrisas) las dos respuestas más originales y creativas serán las ganadoras de 15 boletas cada una. Recuerda que puedes acompañar tus respuestas de un texto explicativo también, pero lo más importante son las imágenes, fotos, o video.
.row
  .span12
    %p
      Para concursar ingresa tu respuesta aquí ó envíala a info@consonrisas.org.
      %b Contemplaremos las respuestas enviadas hasta las 11:59 p.m. del 11 de Marzo.
    %p
      %b Requisitos, Recomendaciones y Reglas:
.row
  .span6
    %ul
      %li
        Para poder acceder a este concurso tu fundación debe haber participado de algun evento nuestro, ej: show en tu fundación, en un teatro, concursos anteriores u otra actividad y debe estar registrada como proyecto social en: www.consonrisas.org/proyectos

      %li Tu fundación debe atender a niños, niñas o jóvenes, recomendamos que los niños que vayan al evento sean mayores de 10 años, por la duración del show.
      %li Deben informar si pueden llenar los 15 cupos (o cuantos podrían llenar), ten en cuenta que estos cupos incluyen a los los acompañantes o adultos responsables.
      %li La fundación se debe encargar de la cotización del transporte y comunicarla como parte de la respuesta del concurso para estudiar la posibilidad de apoyo financiero para este (máximo se apoyará con el 50% puede no existir apoyo para el transporte).
  .span6
    %ul
      %li El show dura 2 horas y media, por lo que deberán planear la salida hacia las 10:00 p.m.

      %li La fundación debe llegar al sitio del espectáculo a las 6:50 p.m. ya que la las puertas se abren a las 7:00 p.m. Si llegan tarde no podrán tener acceso al espectáculo.
      %li
        Este concurso es para
        %b fundaciones
        , no para individuos.
      %li
        Dirección del espectáculo:
        %b Parqueadero de Salitre Mágico Calle 63 con Av. carrera 68.

      %li
        Ya que la jornada será larga tener presente un refrigerio para los niños antes o después del espectáculo, este correrá por cuenta de la fundación.
= render 'form'

- if member_signed_in? and current_member.try(:admin?)
  = link_to 'Back', contests_path

app/views/contests/show.html.haml
- if notice
  Hemos recibido tu participación en el concurso, estaremos anunciando los ganadores el 15 de Marzo por nuestras redes y en el correo que ingresaste, muy pendientes! Y la mejor de las suertes! Recuerda que si quieres contactarnos, porfavor hacerlo a:
  = mail_to "info@consonrisas.org", "info@consonrisas.org"
%p
  %b Fundación:
  = Fundation.find(@contest.fundation_id).name
%p
  %b Número de entradas:
  = @contest.num_tickets
%p
  %b Email:
  = @contest.email
- unless @contest.pic.url(:profile).include? "missing"
  %p
    = image_tag @contest.pic.url(:profile)
- unless @contest.video.empty?
  %p
    %b Video:
    = @contest.video_html
- unless @contest.story.empty?
  %p
    %b Historia:
    = @contest.story
= link_to 'Si necesitas, puedes editar tu respuesta', edit_contest_path(@contest)