config/routes.rb
Consonrisas::Application.routes.draw do
  
  resources :contests

  get "/corteo" => "contests#new", :as => :corteo

  resources :need_categories

  get "need/create"

  get "need/destroy"
  
  get "project_need/create"

  get "project_need/destroy"

  resources :news

  get "search/find"

  match '/auth/facebook/logout' => 'application#facebook_logout', :as => :facebook_logout
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  
  resources :authentications

  devise_for :members, :controllers => {:registrations => 'registrations'}
  get "admin/index"
  match 'admin/', :controller => 'admin', :action => 'index'
  match 'admin/db/:table_name.:format', :controller => 'admin', :action => 'get_table_data'  
  match 'admin/db/:table_name/:id', :controller => 'admin', :action => 'update_table_data', :conditions => {:method => :put }  
  match 'admin/db/:table_name', :controller => 'admin', :action => 'create_table_data', :conditions => {:method => :post}
  match 'admin/db/delete/:table_name/:id', :controller => 'admin', :action => 'delete_table_data', :conditions => {:method => :delete }    
  get "admin/members_to_csv" =>"admin#members_to_csv"
  get "admin/fundation_admins_to_csv" =>"admin#fundation_admins_to_csv"  
  get "admin/events_to_csv" =>"admin#events_to_csv"  
  get "admin/fundations_to_csv" =>"admin#fundations_to_csv"  

  
  get "admin/dj_all", :as => :dj_all

  get "admin/dj_show/:id"=> "admin#dj_show"

  get "admin/dj_destroy/:id" => "admin#dj_destroy"
  
  get "admin/workers" => "admin#see_workers"
  
  post "admin/set_workers" => "admin#set_workers"
  

  get "events/gallery"
  
  get "events/all_events"

  post "events/add_facilitator"
  post "events/add_facilitators"  
  post "events/add_fundation"
  post "events/add_fundations"  
  post "events/add_provider"
  post "events/add_providers"  
  post "events/add_show"  
  
  post "events/remove_facilitator"
  post "events/remove_fundation"
  post "events/remove_provider"  
  
  post "fundations/add_follower"
  post "fundations/remove_follower"
  post "fundations/send_msg_to_admins"    
  
  post "providers/add_follower"
  post "providers/remove_follower"
  post "providers/send_msg_to_admins"  
  
  post "facilitators/add_follower"
  post "facilitators/remove_follower"
  post "facilitators/send_msg"
  
  post "fundations/ask_admin"
  post "providers/ask_admin"  
  post "events/ask_admin"  
  
  post "members/respond_fundation_admin"
  post "members/respond_provider_admin"
  post "members/respond_event_admin"    
  match "members/edit_settings"  => "members#edit_settings", :as => :edit_settings
  post "members/delete_alert"      
  get "members/:id/get_fundations" => "members#get_fundations" 
  post "members/check_email" => "members#check_email"
  post "fundations/check_name" => "fundations#check_name"

  root :to => "home#new_index"
  
  get "/info" =>"home#info"

  get "home/new_index"
  get "home/event_comments"
  get "/social" => "home#social"
  get "/mobile" => "home#mobile"
  post "home/feedback"
  
  post "/cleanInitialSession" => "members#cleanInitialSession"
  
  get 'photos/poll'
  

  
  match 'needs/complete/:id' => 'needs#complete'

  get "/facilitators/list" => "facilitators#list"  
 

  
  resources :roles

  resources :members do
    post "update_facebook_id"
    put "change_pic"  
    get "my_invites"
    get "my_msgs"
    post "seen_msgs"
    post "seen_invites"
  end
  post "/members_register" => "members#register"
  post "/accept_invite/:event_id/:role_id" => "members#accept_invite"
  post "/reject_invite/:event_id/:role_id" => "members#reject_invite"  

  resources :populations

  get "/landing" => "home#landing"
  match "project_needs/all_needs", :as => "all_needs"
  match "project_needs/all_needs_landing", :as => "all_needs_landing"  
  get "/soyproyecto" => "home#landing_fundations"
  get "/soyfacilitador" => "home#landing_facilitators"
  get "/soyproveedor" => "home#landing_providers"    
  get "/legal" => "home#legal"

  localized(['es', 'en'], :verbose => true) do
    get "/contact" => "home#contact", :as => :contact
    get "/touch" =>"home#touch", :as => :touch
    get "/donate" =>"home#donate", :as => :donate
    get "/dona" =>"home#donate", :as => :donate
    get "/allies" =>"home#allies",  :as => :allies
    get "/services" => "home#services", :as => :services
    
    resources :events do
      get 'show_gallery'
      resources :photos
      resources :comments
      resources :needs do
          post "complete"
      end
    end  
    resources :facilitators
    resources :providers do
      get "get_pic"
      put "change_pic"
      resources :shows
      resources :contact_informations
    end
    resources :fundations do
      put "change_pic"    
      get "needs"
      resources :contact_informations
      resources :project_needs do
        get 'need'
        post 'help'
      end
         
    end
  end

end

app/views/shared/_create_buttons.html.haml
.create-buttons
  .create-provider-div
    %a{:class => "create-provider create-button #{'register_wizzard' unless member_signed_in?}", :href=>"/providers/new", :create=>"provider"}          
      = image_tag("CrearProveedorBoton.png", :class=>"create-provider-img")
      %span.desc-new-provider
        .desc-create-triangle    
        Si eres artista y estás dispuesto a generar momentos mágicos llenos de sonrisas
  .create-fundation-div
    %a{:class => "create-fundation create-button #{'register_wizzard' unless member_signed_in?}", :href=>"/fundations/new", :create=>"fundation"}
      = image_tag("CrearProyectosBoton.png", :class=>"create-fundation-img")
      %span.desc-new-fundation
        .desc-create-triangle
        Si trabajas para mejorar la calidad de vida de los demás
  .create-event-div
    %a{:class => "create-event create-button #{'register_wizzard' unless member_signed_in?}", :href=>"/events/new", :create=>"event"}      
      = image_tag("CrearEventosBoton.png", :class=>"create-event-img")
      %span.desc-new-event
        .desc-create-triangle    
        Crea un evento para que un proyecto social sonria

app/views/shared/_create_event_button.html.haml
.create-buttons-shared
  .create-event-div
    %a{:class => "create-event create-button #{'register_wizzard' unless member_signed_in?}", :href=>"/events/new", :create=>"event", :style=>"width:100%;"}      
      = image_tag("CrearEventosBoton.png", :class=>"create-event-img")

app/views/shared/_create_fundation_button.html.haml
.create-buttons-shared
  .create-fundation-div
    %a{:class => "create-fundation create-button #{'register_wizzard' unless member_signed_in?}", :href=>"/fundations/new", :create=>"fundation", :style=>"width:100%;"}
      = image_tag("CrearProyectosBoton.png", :class=>"create-fundation-img")

app/views/shared/_create_provider_button.html.haml
.create-buttons-shared
  .create-provider-div
    %a{:class => "create-provider create-button #{'register_wizzard' unless member_signed_in?}", :href=>"/providers/new", :create=>"provider", :style=>"width:100%; height:100%"}
      = image_tag("CrearProveedorBoton.png", :class=>"create-provider-img")

app/views/shared/_footer.html.haml
#footer
  = render :partial =>"/shared/on_media"
  .row
    .span12.inner-footer
      %a{:target=>"_blank" , :href=>"http://www.ligasonrisas.org/equipo-con-sonrisas.html"} Equipo
      #{" | "}                
      %a{:href=>"/servicios"} Servicios
      #{" | "}          
      %a{:href=>"/apoyo"} Apoyo
      #{" | "}
      %a{:href=>"/aliados"} Aliados
      #{" | "}
      %a{:href=>"/legal"} Términos y Condiciones
      #{" | "}
      %a{:href=>"/contacto"} Contáctanos
      #{" | "}      
      %a{:href=>"/social", :title=> "Conéctate en nuestras redes sociales"} Síguenos
      %a{:href=>"http://www.twitter.com/consonrisas", :class=>"footernostyle", :target=>"_blank"}
        %img{:src=>"/images/TwitterBtn.png", :alt=>"Follow consonrisas on Twitter", :title=>"Follow consonrisas on Twitter"}  
      %a{:href=>"http://www.facebook.com/consonrisas", :class=>"footernostyle", :target=>"_blank"}
        %img{:src=>"/images/FacebookBtn.png",:alt=>"Follow Conectando Sonrisas on Facebook",:title=>"Follow Conectando Sonrisas on Facebook"}
      %a{:href=>"http://vimeo.com/consonrisas", :class=>"footernostyle", :target=>"_blank"}
        %img{:src=>"/images/VimeoBtn.png", :alt=>"Vimeo", :title=>"Follow Conectando Sonrisas on Vimeo"}      
- unless member_signed_in?
  = render :partial => "/home/register_steps"
  #register-form{:style=>"display:none"}
    = render :partial => "/registrations/new"        

app/views/shared/_just_pic.html.erb
<%= javascript_include_tag 'jsUpload/jquery.fileupload', 'jsUpload/jquery.fileupload-ui' %>
<%= image_tag @model.pic.url(:profile), :class=>"img-profile" %>
<%= form_for(@model, :url=> request.path + "/change_pic", :html => { :class => "upload2", :multipart=> true}) do |f| %>
<script type="text/javascript">
jQuery(document).ready(function($) {
  $('.upload2').each(function(){

    if (!$(this).hasClass('applied')){
      $(this).addClass('applied').fileUploadUI({
            uploadTable: jQuery('.upload_files2'),
            buildUploadRow: function (files, index) {
                var file = files[index];
                return jQuery('<tr><td>' + file.name + '<\/td>' +
                        '<td class="file_upload_progress"><div><\/div><\/td>' +
                        '<td class="file_upload_cancel">' +
                        '<button class="ui-state-default ui-corner-all" title="Cancel">' +
                        '<span class="ui-icon ui-icon-cancel">Cancel<\/span>' +
                        '<\/button><\/td><\/tr>');
            },
            buildDownloadRow: function (file) {
                return jQuery('<tr><td><img alt="Photo" width="40" height="40" src="' + file.pic_path + '">' + file.name + '<\/td><\/tr>');
            },
            onComplete: onCompleteCallback
        });       
    }
    
  
  });
});
function onCompleteCallback (event, files, index, xhr, handler) {
    var json = handler.response;
    jQuery(".img-profile").attr("src", json.pic_path_big);
    setTimeout(clearUploaded, 2500);
}
function clearUploaded(){
  jQuery('.upload_files2').html("");
}
</script>

  <%= f.file_field :pic %>
  <div>Sube una foto (5MB max)</div>

<% end %>
  <table class="upload_files2"></table>
  <table class="download_files2"></table>

app/views/shared/_menu.html.haml
.div-for-menu-space.hidden-phone{:style=>"padding-top:70px"}
.menu-bar.hidden-phone
  .menu-inner-bar
    %ul.container
      %li.visible-tablet
        %a.menu-logo-link{:href=>"/"}
          = image_tag "/photos/thumb/missing.png"
      %li.hidden-tablet
        %a.menu-logo-link{:href=>"/"}
          - if Date.today.mon == 12
            = image_tag "/images/LogoNavidad.png", :class=> "menu-logo", :style=>"width:90px"
          - else
            = image_tag "menu/MenuLogo_small_green.png", :class=> "menu-logo"
      %li
        %a.cont{:href=>"#{member_path(current_member.id)}"}
          %span.menu-home
          .menu-home-txt.menu-home-text
            inicio
          %span.tooltip.tooltip-inicio
            .menu-logo-triangle
            inicio        
      %li
        %a.cont{:class => "#{'msgs' if request.fullpath.include? 'member'}", :href => request.fullpath.include?("member") ? "#msgs" : member_path(current_member.id) << "#msgs"}
          - if current_member.num_new_msgs > 0
            #num_new_msgs.num_new
              = current_member.num_new_msgs
          %span.menu-messages
          .menu-messages-txt.menu-messages-text
            mensajes    
          %span.tooltip
            .menu-logo-triangle
            mensajes                
      %li
        %a.cont{:class => "#{'invites' if request.fullpath.include? 'member'}", :href => request.fullpath.include?("member") ? "#invites" : member_path(current_member.id) << "#invites"}
          - if current_member.num_new_invites > 0 
            #num_new_invites.num_new
              = current_member.num_new_invites
          %span.menu-invitations
          .menu-invitations-txt.menu-invitations-text
            invitaciones          
          %span.tooltip.tooltip-grande
            .menu-logo-triangle
            invitaciones        
      %li
        %a.cont{:href=>"/project_needs/all_needs"}
          %span.menu-help
          .menu-help-txt.menu-help-text
            ayuda        
          %span.tooltip
            .menu-logo-triangle
            ayuda
      %li
        .cont.container-box
          %span.menu-register-events
          .menu-register-events-txt.menu-register-events-text
            eventos    
          .create-buttons
            .create-buttons-text
              eventos
            .create-event-div
              %a{:class => "create-event create-button", :href=>"/events/new"}      
                %br
                = "&nbsp".html_safe
                = "&nbsp".html_safe
                nuevo
                = "&nbsp".html_safe                                
            %br
            .create-event-div
              %a{:class => "create-event create-button", :href=>"/eventos"}
                %br
                = "&nbsp".html_safe
                = "&nbsp".html_safe                
                todos
                = "&nbsp".html_safe                                
      %li
        .cont.container-box
          %span.menu-register-fundations
          .menu-register-fundations-txt.menu-register-fundations-text
            proyectos          
          .create-buttons
            .create-buttons-text          
              proyectos sociales
            .create-fundation-div
              %a{:class => "create-fundation create-button", :href=>"/fundations/new"}
                %br
                = "&nbsp".html_safe
                = "&nbsp".html_safe
                nuevo
                = "&nbsp".html_safe                                
            %br                
            .create-fundation-div
              %a{:class => "create-fundation create-button", :href=>"/proyectos"}
                %br
                = "&nbsp".html_safe
                = "&nbsp".html_safe
                todos    
                = "&nbsp".html_safe                                            
      %li
        .cont.container-box
          %span.menu-register-providers
          .menu-register-providers-txt.menu-register-providers-text
            proveedores          
          .create-buttons      
            .create-buttons-text          
              proveedores de sonrisas        
            .create-provider-div
              %a{:class => "create-provider create-button", :href=>"/providers/new"}          
                %br              
                = "&nbsp".html_safe
                = "&nbsp".html_safe
                nuevo
                = "&nbsp".html_safe                                
            %br                
            .create-provider-div
              %a{:class => "create-provider create-button", :href=>"/proveedores"}          
                %br
                = "&nbsp".html_safe
                = "&nbsp".html_safe                
                todos
                = "&nbsp".html_safe                                
      %li 
        .search-div{:style=>"display:inline-block;line-height:4em;"}
          %form#searchform_new{:action => "/search/find", :method => "get"}
            %input#search-text-new.search-text.default{:name => "find", :type => "text", :style=>"color:green; width:150px;margin-left:8px;"}
            %span.close-search{:style=>"color:white;display:none;font-weight:bold;border:1px white;cursor:pointer"} x 
      %li
        .my-account-links
          .member-info.hidden-tablet
            = member_name(current_member)        
          .show-edit-options
            = image_tag member_thumb(current_member.facilitator), :class=>"mini-img-profile"  
            %span.edit-my-account-options
              .edit-me-container{:style=>"border-bottom: 1px dotted white;padding:3px;"}       
                %a.edit-me-menu{:type=>"button", :href=>"/members/edit_settings#my-profile"} Editar Mi Perfil
              .edit-me-container{:style=>"border-bottom: 1px dotted white;padding:3px;"}
                %a.edit-me-menu{:type=>"button", :href=>"/members/edit_settings#my-account"} Editar Mi Cuenta
              .edit-me-container{:style=>"padding:3px;"}
                - if session[:fb_token].nil?
                  = link_to I18n.t('account.logout'), destroy_member_session_path, :class=>"edit-me-menu"
                - else
                  = link_to I18n.t('account.logout'), facebook_logout_path, :class=>"edit-me-menu"
              - if current_member.try(:admin?)
                .edit-me-container{:style=>"border-bottom: 1px dotted white;padding:3px;"}
                .edit-me-container{:style=>"padding:3px;"}
                  = link_to 'admin' , '/admin', :class=>"edit-me-menu"

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}", :style=>"position: relative; z-index: 1090; margin-top: 10px;"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/shared/_mobile_nav.html.haml
.navbar.navbar-fixed-top.visible-phone
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{:href => "/", :style=>"text-decoration:none"} Conectando Sonrisas
      .nav-collapse
        %ul.nav{:style=>"margin-left:-40px;"}
          %li.home-mobile-menu.active
            = link_to member_path(current_member.id) do
              %i.icon-home
              Inicio
          %li.needs-mobile-menu
            %a{:href=>"/project_needs/all_needs"}
              %i.icon-star
              Ayuda
          %li.events-mobile-menu
            %a{:href=>"/eventos"}
              %i.icon-th-list
              Eventos
          %li.providers-mobile-menu
            %a{:href=>"/proveedores"}
              %i.icon-user            
              Proveedores de Sonrisas
          %li.fundations-mobile-menu
            %a{:href=>"/proyectos"}
              %i.icon-user            
              Proyectos Sociales               
          %li.edit-mobile-menu
            %a{:href=>"/members/edit_settings"}
              %i.icon-edit            
              Editar mi perfil                 
          %li
            - if session[:fb_token].nil?
              = link_to destroy_member_session_path, :class=>"edit-me-menu" do
                %i.icon-off
                = I18n.t('account.logout')
            - else
              = link_to facebook_logout_path, :class=>"edit-me-menu" do
                %i.icon-off
                = I18n.t('account.logout')
          - if current_member.try(:admin?)
            %li
              %a{:href=>"/admin"}
                %i.icon-edit
                Admin

app/views/shared/_old_menu.html.haml
.menu-bar
  .menu-inner-bar
    %ul
      %li
        %a.menu-logo-link{:href=>"/"}
          .menu-logo  
      %li
        %a.container{:href=>"#{member_path(current_member.id)}"}
          %span.menu-home
          .menu-home-text
            Inicio
          %span.tooltip.tooltip-inicio
            .menu-logo-triangle
            Inicio        
      %li
        %a.container{:class => "#{'msgs' if request.fullpath.include? 'member'}", :href => request.fullpath.include?("member") ? "#msgs" : member_path(current_member.id) << "#msgs"}
          %span.menu-messages
          .menu-messages-text
            Mensajes    
          %span.tooltip
            .menu-logo-triangle
            Mensajes                
      %li
        %a.container{:class => "#{'invites' if request.fullpath.include? 'member'}", :href => request.fullpath.include?("member") ? "#invites" : member_path(current_member.id) << "#invites"}
          %span.menu-invitations
          .menu-invitations-text
            Invitaciones          
          %span.tooltip.tooltip-grande
            .menu-logo-triangle
            Invitaciones        
      %li
        %a.container{:href=>"/project_needs/all_needs"}
          %span.menu-help
          .menu-help-text
            Ayuda        
          %span.tooltip
            .menu-logo-triangle
            Ayuda
      %li
        .container
          %span.menu-register-events
          .menu-register-events-text
            Eventos    
          .create-buttons
            .create-buttons-text
              Eventos
            .create-event-div
              %a{:class => "create-event create-button", :href=>"/events/new"}      
                = image_tag("CrearEventosBoton.png", :class=>"create-event-img")
            .create-event-div
              %a{:class => "create-event create-button", :href=>"/eventos"}
                = "&nbsp".html_safe
                = "&nbsp".html_safe              
                ver
                %br
                = "&nbsp".html_safe
                = "&nbsp".html_safe                
                todos
      %li
        .container
          %span.menu-register-fundations
          .menu-register-fundations-text
            Proyectos          
          .create-buttons
            .create-buttons-text          
              Proyectos Sociales
            .create-fundation-div
              %a{:class => "create-fundation create-button", :href=>"/fundations/new"}
                = image_tag("CrearProyectosBoton.png", :class=>"create-fundation-img")
            .create-fundation-div
              %a{:class => "create-fundation create-button", :href=>"/proyectos"}
                = "&nbsp".html_safe
                = "&nbsp".html_safe
                ver 
                %br
                = "&nbsp".html_safe
                = "&nbsp".html_safe
                todos                
      %li
        .container
          %span.menu-register-providers
          .menu-register-providers-text
            Proveedores          
          .create-buttons      
            .create-buttons-text          
              Proveedores de Sonrisas        
            .create-provider-div
              %a{:class => "create-provider create-button", :href=>"/providers/new"}          
                = image_tag("CrearProveedorBoton.png", :class=>"create-provider-img")
            .create-provider-div
              %a{:class => "create-provider create-button", :href=>"/proveedores"}          
                = "&nbsp".html_safe
                = "&nbsp".html_safe              
                ver
                %br
                = "&nbsp".html_safe
                = "&nbsp".html_safe                
                todos
      %li 
        .search-div{:style=>"display:inline-block;line-height:4em;"}
          %form#searchform_new{:action => "/search/find", :method => "get"}
            %input#search-text-new.search-text.default{:name => "find", :type => "text", :style=>"color:green;"}
            %span.close-search{:style=>"color:white;display:none;font-weight:bold;border:1px white;cursor:pointer"} x 
      %li
        .my-account-links
          .member-info
            = member_name(current_member)        
          .show-edit-options
            = image_tag member_thumb(current_member.facilitator), :class=>"mini-img-profile"  
            %span.edit-my-account-options
              .edit-me-container{:style=>"border-bottom: 1px dotted white;padding:3px;"}       
                %a.edit-me-menu{:type=>"button", :href=>"/members/edit_settings#my-profile"} Editar Mi Perfil
              .edit-me-container{:style=>"border-bottom: 1px dotted white;padding:3px;"}
                %a.edit-me-menu{:type=>"button", :href=>"/members/edit_settings#my-account"} Editar Mi Cuenta
              .edit-me-container{:style=>"padding:3px;"}
                - if session[:fb_token].nil?
                  = link_to I18n.t('account.logout'), destroy_member_session_path, :class=>"edit-me-menu"
                - else
                  = link_to I18n.t('account.logout'), facebook_logout_path, :class=>"edit-me-menu"

app/views/shared/_old_menu_green.html.haml
.menu-bar
  .menu-inner-bar
    %ul
      %li
        %a.menu-logo-link{:href=>"/"}
          .menu-logo  
      %li
        %a.container{:href=>"#{member_path(current_member.id)}"}
          %span.menu-home
          .menu-home-text
            Inicio
          %span.tooltip.tooltip-inicio
            .menu-logo-triangle
            Inicio        
      %li
        %a.container{:class => "#{'msgs' if request.fullpath.include? 'member'}", :href => request.fullpath.include?("member") ? "#msgs" : member_path(current_member.id) << "#msgs"}
          %span.menu-messages
          .menu-messages-text
            Mensajes    
          %span.tooltip
            .menu-logo-triangle
            Mensajes                
      %li
        %a.container{:class => "#{'invites' if request.fullpath.include? 'member'}", :href => request.fullpath.include?("member") ? "#invites" : member_path(current_member.id) << "#invites"}
          %span.menu-invitations
          .menu-invitations-text
            Invitaciones          
          %span.tooltip.tooltip-grande
            .menu-logo-triangle
            Invitaciones        
      %li
        %a.container{:href=>"/project_needs/all_needs"}
          %span.menu-help
          .menu-help-text
            Ayuda        
          %span.tooltip
            .menu-logo-triangle
            Ayuda
      %li
        .container
          %span.menu-register-events
          .menu-register-events-text
            Eventos    
          .create-buttons
            .create-buttons-text
              Eventos
            .create-event-div
              %a{:class => "create-event create-button", :href=>"/events/new"}      
                = image_tag("CrearEventosBoton.png", :class=>"create-event-img")
            .create-event-div
              %a{:class => "create-event create-button", :href=>"/eventos"}
                = "&nbsp".html_safe
                = "&nbsp".html_safe              
                ver
                %br
                = "&nbsp".html_safe
                = "&nbsp".html_safe                
                todos
      %li
        .container
          %span.menu-register-fundations
          .menu-register-fundations-text
            Proyectos          
          .create-buttons
            .create-buttons-text          
              Proyectos Sociales
            .create-fundation-div
              %a{:class => "create-fundation create-button", :href=>"/fundations/new"}
                = image_tag("CrearProyectosBoton.png", :class=>"create-fundation-img")
            .create-fundation-div
              %a{:class => "create-fundation create-button", :href=>"/proyectos"}
                = "&nbsp".html_safe
                = "&nbsp".html_safe
                ver 
                %br
                = "&nbsp".html_safe
                = "&nbsp".html_safe
                todos                
      %li
        .container
          %span.menu-register-providers
          .menu-register-providers-text
            Proveedores          
          .create-buttons      
            .create-buttons-text          
              Proveedores de Sonrisas        
            .create-provider-div
              %a{:class => "create-provider create-button", :href=>"/providers/new"}          
                = image_tag("CrearProveedorBoton.png", :class=>"create-provider-img")
            .create-provider-div
              %a{:class => "create-provider create-button", :href=>"/proveedores"}          
                = "&nbsp".html_safe
                = "&nbsp".html_safe              
                ver
                %br
                = "&nbsp".html_safe
                = "&nbsp".html_safe                
                todos
      %li 
        .search-div{:style=>"display:inline-block;line-height:4em;"}
          %form#searchform_new{:action => "/search/find", :method => "get"}
            %input#search-text-new.search-text.default{:name => "find", :type => "text", :style=>"color:green;"}
            %span.close-search{:style=>"color:white;display:none;font-weight:bold;border:1px white;cursor:pointer"} x 
      %li
        .my-account-links
          .member-info
            = member_name(current_member)        
          .show-edit-options
            = image_tag member_thumb(current_member.facilitator), :class=>"mini-img-profile"  
            %span.edit-my-account-options
              .edit-me-container{:style=>"border-bottom: 1px dotted white;padding:3px;"}       
                %a.edit-me-menu{:type=>"button", :href=>"/members/edit_settings#my-profile"} Editar Mi Perfil
              .edit-me-container{:style=>"border-bottom: 1px dotted white;padding:3px;"}
                %a.edit-me-menu{:type=>"button", :href=>"/members/edit_settings#my-account"} Editar Mi Cuenta
              .edit-me-container{:style=>"padding:3px;"}
                - if session[:fb_token].nil?
                  = link_to I18n.t('account.logout'), destroy_member_session_path, :class=>"edit-me-menu"
                - else
                  = link_to I18n.t('account.logout'), facebook_logout_path, :class=>"edit-me-menu"

app/views/shared/_on_media.html.haml
.on-media
  .row
    .span4
      .media-text
        En los medios:
  .row
    .span4{:style=>"text-align: center"}
      %a{:href=>"https://www.youtube.com/watch?v=ICvnXJYRVZo", :target=>"_blank"}
        = image_tag "http://www.ligasonrisas.org/uploads/8/6/4/5/8645542/2026425.png"
    .span4{:style=>"text-align: center"}
      %a{:href=>"http://www.eltiempo.com/gente/red-social-colombiana-conectando-sonrisas_12658324-4", :target=>"_blank"}
        = image_tag "eltiempo.png"
    .span4{:style=>"text-align: center"}
      %a{:href=>"http://www.canalrcnmsn.com/content/red_social_conectando_sonrisas", :target=>"_blank"}
        = image_tag "rcn.png"