config/routes.rb
Consonrisas::Application.routes.draw do
  
  resources :contests

  get "/corteo" => "contests#new", :as => :corteo

  resources :need_categories

  get "need/create"

  get "need/destroy"
  
  get "project_need/create"

  get "project_need/destroy"

  resources :news

  get "search/find"

  match '/auth/facebook/logout' => 'application#facebook_logout', :as => :facebook_logout
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  
  resources :authentications

  devise_for :members, :controllers => {:registrations => 'registrations'}
  get "admin/index"
  match 'admin/', :controller => 'admin', :action => 'index'
  match 'admin/db/:table_name.:format', :controller => 'admin', :action => 'get_table_data'  
  match 'admin/db/:table_name/:id', :controller => 'admin', :action => 'update_table_data', :conditions => {:method => :put }  
  match 'admin/db/:table_name', :controller => 'admin', :action => 'create_table_data', :conditions => {:method => :post}
  match 'admin/db/delete/:table_name/:id', :controller => 'admin', :action => 'delete_table_data', :conditions => {:method => :delete }    
  get "admin/members_to_csv" =>"admin#members_to_csv"
  get "admin/fundation_admins_to_csv" =>"admin#fundation_admins_to_csv"  
  get "admin/events_to_csv" =>"admin#events_to_csv"  
  get "admin/fundations_to_csv" =>"admin#fundations_to_csv"  

  
  get "admin/dj_all", :as => :dj_all

  get "admin/dj_show/:id"=> "admin#dj_show"

  get "admin/dj_destroy/:id" => "admin#dj_destroy"
  
  get "admin/workers" => "admin#see_workers"
  
  post "admin/set_workers" => "admin#set_workers"
  

  get "events/gallery"
  
  get "events/all_events"

  post "events/add_facilitator"
  post "events/add_facilitators"  
  post "events/add_fundation"
  post "events/add_fundations"  
  post "events/add_provider"
  post "events/add_providers"  
  post "events/add_show"  
  
  post "events/remove_facilitator"
  post "events/remove_fundation"
  post "events/remove_provider"  
  
  post "fundations/add_follower"
  post "fundations/remove_follower"
  post "fundations/send_msg_to_admins"    
  
  post "providers/add_follower"
  post "providers/remove_follower"
  post "providers/send_msg_to_admins"  
  
  post "facilitators/add_follower"
  post "facilitators/remove_follower"
  post "facilitators/send_msg"
  
  post "fundations/ask_admin"
  post "providers/ask_admin"  
  post "events/ask_admin"  
  
  post "members/respond_fundation_admin"
  post "members/respond_provider_admin"
  post "members/respond_event_admin"    
  match "members/edit_settings"  => "members#edit_settings", :as => :edit_settings
  post "members/delete_alert"      
  get "members/:id/get_fundations" => "members#get_fundations" 
  post "members/check_email" => "members#check_email"
  post "fundations/check_name" => "fundations#check_name"

  root :to => "home#new_index"
  
  get "/info" =>"home#info"

  get "home/new_index"
  get "home/event_comments"
  get "/social" => "home#social"
  get "/mobile" => "home#mobile"
  post "home/feedback"
  
  post "/cleanInitialSession" => "members#cleanInitialSession"
  
  get 'photos/poll'
  

  
  match 'needs/complete/:id' => 'needs#complete'

  get "/facilitators/list" => "facilitators#list"  
 

  
  resources :roles

  resources :members do
    post "update_facebook_id"
    put "change_pic"  
    get "my_invites"
    get "my_msgs"
    post "seen_msgs"
    post "seen_invites"
  end
  post "/members_register" => "members#register"
  post "/accept_invite/:event_id/:role_id" => "members#accept_invite"
  post "/reject_invite/:event_id/:role_id" => "members#reject_invite"  

  resources :populations

  get "/landing" => "home#landing"
  match "project_needs/all_needs", :as => "all_needs"
  match "project_needs/all_needs_landing", :as => "all_needs_landing"  
  get "/soyproyecto" => "home#landing_fundations"
  get "/soyfacilitador" => "home#landing_facilitators"
  get "/soyproveedor" => "home#landing_providers"    
  get "/legal" => "home#legal"

  localized(['es', 'en'], :verbose => true) do
    get "/contact" => "home#contact", :as => :contact
    get "/touch" =>"home#touch", :as => :touch
    get "/donate" =>"home#donate", :as => :donate
    get "/dona" =>"home#donate", :as => :donate
    get "/allies" =>"home#allies",  :as => :allies
    get "/services" => "home#services", :as => :services
    
    resources :events do
      get 'show_gallery'
      resources :photos
      resources :comments
      resources :needs do
          post "complete"
      end
    end  
    resources :facilitators
    resources :providers do
      get "get_pic"
      put "change_pic"
      resources :shows
      resources :contact_informations
    end
    resources :fundations do
      put "change_pic"    
      get "needs"
      resources :contact_informations
      resources :project_needs do
        get 'need'
        post 'help'
      end
         
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def new_index
    @num_facilitators = Facilitator.count
    @num_fundations = Fundation.count
    @num_providers = Provider.count    
    @num_events = Event.count    
    @comments = []
    @photos = []
    @photos = Photo.find(:all, :order => "id desc", :limit => 15)    
#    p_ids = 15.times.map{ rand(Photo.count) }
#    p_ids.each do |p_id|
#      begin
#        p = Photo.find(p_id)
#        @photos << p if p
#      rescue
#        
#      end
#    end      
  end
  
  def index
    @facilitators = Facilitator.count
    @fundations = Fundation.count
    @providers = Provider.count    
    @events = Event.count    
    
    @photos = []
    @comments = []
    @photos = Photo.find(:all, :order => "id desc", :limit => 15)
#    p_ids = 15.times.map{ rand(Photo.count) }
#    p_ids.each do |p_id|
#      begin
#        p = Photo.find(p_id)
#        @photos << p if p
#      rescue
#        
#      end
#    end      
  end
    
  def event_comments
    @comments = Comment.find(:all, :order => "id desc", :limit => 10)
#    @comments = []
#    c_ids = 10.times.map{ rand(Comment.count) }
#    c_ids.each do |c_id|
#      begin
#        c = Comment.find(c_id)
#        @comments << c if c and c.event
#      rescue
#      end
#    end    
    render :layout => false
  end

  def info
    
  end
  def touch
  end
  
  def legal
  end
  
  def contact
  end
  
  def feedback
    Feedback.create(:message=> params[:men])
    respond_to do |format|
      format.js {head:ok}
    end
  end
  
  def social
  end
  
  def allies
  end
  
  def donate
  end  
  
  def services
  end
  
  def landing
  end
  
  def landing_fundations
    if member_signed_in?
      redirect_to member_path current_member
    else
      @fundation = Fundation.new
      render :layout => "landing"
    end
  end
  
  def landing_facilitators
    if member_signed_in?
      redirect_to member_path current_member
    else
      @facilitator = Facilitator.new
      @total_needs = ProjectNeed.all.count
      @no_cat_needs = ProjectNeed.where("need_category_id IS NULL")
      @need_categories = NeedCategory.all      
      render :layout => "landing"
    end
  end
  
  def landing_providers
    if member_signed_in?
      redirect_to member_path current_member
    else
      @events = Event.order("date DESC").page(params[:page]).per(8)    
      @provider = Provider.new
      render :layout => "landing"
    end
  end    
  
  def mobile
    @events = Event.all
    render :layout => false
  end
  
end 

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_events_photos.html.haml
#makeMeScrollable
  .scrollingHotSpotLeft
  .scrollingHotSpotLeftVisible
  .scrollingHotSpotRight
  .scrollingHotSpotRightVisible
  .scrollWrapper
    .scrollableArea
      - @photos.each do |p|
        = image_tag(p.photo.url(:big), :class=>"home_pic")

app/views/home/_landing_slider.html.erb
<div id="wrapper">
   <div class="slider-wrapper theme-default">
        <div class="ribbon"></div>
        <div id="slider" class="nivoSlider">
          <img src="https://s3.amazonaws.com/conectandosonrisas/home/1.JPG" alt=""/>
          <img src="https://s3.amazonaws.com/conectandosonrisas/home/2.JPG" alt="" data-transition="slideInLeft" />
          <img src="https://s3.amazonaws.com/conectandosonrisas/home/3.jpg" alt="" />        
          <img src="https://s3.amazonaws.com/conectandosonrisas/home/4.jpg" alt="" />        
        </div>     
</div>

<%= javascript_include_tag "nivo-slider/jquery.nivo.slider.pack.js"%>
<script type="text/javascript">
var $jq = jQuery.noConflict();
$jq(document).ready(function($) {    
    $jq('#slider').nivoSlider();        
});
</script>

app/views/home/_register_steps.html.erb
<div id="register_steps" style="display:none">
  <form id="wizzard_form" action="/members" method="POST">
  <div style="margin:0;padding:0;display:inline">
    <input type="hidden" value="✓" name="utf8">
    <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token">
  </div>  
  
    <div id="wizard" class="swMain">
      <ul>
        <li><a href="#step-1">
              <label class="stepNumber">1</label>
              <span class="stepDesc">
                 Login<br />
                 <small>Email y clave</small>
              </span>
          </a></li>
        <li><a href="#step-2">
              <label class="stepNumber">2</label>
              <span class="stepDesc">
                 Datos<br />
                 <small>Para generar sonrisas</small>
              </span>
          </a></li>
      </ul>
      <div id="step-1">   
          <h2 class="StepTitle">Datos de Registro</h2>
           <!-- step content -->
          <table>
          <tr>
          <td>
          <br />
          Email:<br />
          <input type="text" size="30" name="member[email]" id="email_reg">
          <span id="email_warning" class="warning" style="display:none"></span>
          <br/>
          <%= I18n.t('account.password') %>:<br />
          <input type="password" size="30" id="pass_reg" name="member[password]"/>
          <span id="pass_warning" class="warning" style="display:none"></span>
          <br />
          <%= I18n.t('account.password_confirmation') %>:<br />
          <input type="password" size="30" id="pass_confirm_reg" name="member[password_confirmation]"/>
          <span id="pass_confirm_warning" class="warning" style="display:none"></span>        
          </td>
          <td style="text-align:left">
          
          <h3 style="text-align:center">
            ¿Cómo quieres conectar sonrisas?
          </h3>
            <div class="type_divs">
            <%= image_tag "IconosFacilitadores.png", :style=>"vertical-align:middle; height:60px", :class=>"img-rounded" %>
            <input type="checkbox" id="reg_facilitator" value="true" name="isFacilitator" /> <%= I18n.t('facilitator_name') %> - Si tu o tu empresa tienes ganas de ayudar
            </div>
            <div class="type_divs">
            <%= image_tag "IconosProyectosSociales.png", :style=>"vertical-align:middle; height:60px;", :class=>"img-rounded" %>
            <input type="checkbox" id="reg_fundation" value="true" name="isFundation" /> <%= I18n.t('fundation_name')%> - Si trabajas para mejorar la calidad de vida de las personas
            </div>
            <div class="type_divs">
            <%= image_tag "IconosProveedores.png", :style=>"vertical-align:middle; height:60px;", :class=>"img-rounded" %>            
            <input type="checkbox" id="reg_provider" value="true" name="isProvider" /> <%= I18n.t('provider_name') %> - Si tienes algún producto o servicio que genere sonrisas
            </div>
            </td>
            </tr>
            <tr>
            <td colspan="2" style="text-align:center">
          <!--  <p>
          Puedes ingresar con estos servicios:
              </p>
          <a href="/auth/facebook">
            <%= image_tag "signin_facebook_small.png", :alt => "Facebook", :title=>"Sign in with facebook" %>  </a>
             &nbsp;&nbsp;
             <a href="/auth/twitter">
            <%= image_tag "sign-in-with-twitter-small.png", :alt => "Twitter", :title=>"Sign in with twitter" %>
          </a> -->
          </td>
          </tr>
          </table>
      </div>
      <div id="step-2">
          <h2 class="StepTitle">Completa estos datos importantes</h2> 
           <!-- step content -->
           <div id="reg_facilitator_info" style="display:none;" class="type_divs">
           <%= image_tag "IconosFacilitadores.png", :style=>"vertical-align:middle;height:60px;", :class=>"img-rounded" %>
            <%= I18n.t('name') %>:
            <input type="text" id="reg_facilitator_name" name="member[name]" size="25"/> - Tu nombre
          <span id="reg_facilitator_info_warning" class="warning" style="display:none"></span>                    
           </div>
           <div id="reg_fundation_info"  style="display:none;" class="type_divs">
           <%= image_tag "IconosProyectosSociales.png", :style=>"vertical-align:middle;height:60px;", :class=>"img-rounded" %>
            <%= I18n.t('name') %>:
            <input type="text" id="reg_fundation_name" name="fundation[name]" size="25"/> - El nombre de fundación o proyecto
          <span id="reg_fundation_info_warning" class="warning" style="display:none"></span>                    
           </div>
           <div id="reg_provider_info" style="display:none;" class="type_divs">
           <%= image_tag "IconosProveedores.png", :style=>"vertical-align:middle;height:60px;", :class=>"img-rounded" %>           
            <%= I18n.t('name') %>:
            <input type="text" id="reg_provider_name" name="provider[name]" size="25"/> - El nombre del generador de sonrisas
            
          <span id="reg_provider_info_warning" class="warning" style="display:none"></span>                    
           </div>           
      </div>                      
    </div>
    <div style="width: 50%;margin-left:auto;margin-right: auto;font-size: small;">
    Al registrarte e ingresar aceptas nuestros <a href="/legal" target="_blank">Términos y Condiciones</a></div>
  </form>
  <span class="loader_login" style="display:none"> <%= image_tag "gray-loader.gif" %>  </span>
</div>

app/views/home/allies.html.haml
.row
  .offset2.span8
    %h2.social-title Estos son los aliados de este proyecto
.row
  .offset2.span8
    %p.social-p.centered-content Conectando Sonrisas está profundamente agradecido con todas las personas que han apoyado de una u otra manera este proyecto, a todas ellas los más sinceros agradecimientos. !Los queremos mucho!
.row
  .allies.span6{:style=>"min-height:170px;"}
    = link_to image_tag("LigaDeLasSonrisasLogoTrans.png"), "http://ligasonrisas.org/", :target=>"_blank", :title=>"Visita la Liga de las Sonrisas"
    %p Conectando Sonrisas es un proyecto de la Fundación La Liga de las Sonrisas
  .allies.span6{:style=>"min-height:170px;"}
    = link_to image_tag("dynaco.png"), "http://www.dynaco.co", :target=>"_blank", :title=>"Visita Dynaco"
    %p Dynaco ha aportado sus recursos y conocimiento para lograr la creación de este portal
.row        
  .allies.span6{:style=>"min-height:200px;"}
    = link_to image_tag("s4n.png"), "http://www.seven4n.com", :target=>"_blank", :title=>"Visita Seven4N"
    %p Seven4n ha colaborado con ideas de negocio y con un product manager para este portal
  .allies.span6{:style=>"min-height:200px;"}
    = link_to image_tag("Pato.png"), "http://www.patoalanaranja.com/", :target=>"_blank", :title=>"Visita Pato ala Naranja"
    %p Pato ala Naranja es el responsable del diseño gráfico de la página
.row
  .allies.span12{:style=>"min-height:140px;"}
    = image_tag "ms-logo_bL.png", :style=>"width:220px"
    %p Microsoft cree en nuesta idea, por lo cual hacemos parte de su programa de donación de software.
.row
  .allies.span6{:style=>"min-height:210px;"}
    = link_to image_tag("LogoUniandinos.png", :style=>"height:170px;"), "http://www.uniandinos.org.co", :target=>"_blank", :title=>"Visita Uniandinos"
    %p Asociación de Egresados de la Universidad de Los Andes
  .allies.span6{:style=>"min-height:210px;"}
    = link_to image_tag("asu.png", :style=>"height:170px;"), "http://www.uniandinos.org.co/asu/", :target=>"_blank", :title=>"Visita A la Alianza Social Uniandina"
    %p Hacemos parte del programa de responsabilidad social de uniandinos
.row
  .allies.span6
    = link_to image_tag("MWB-Logo.png"), "http://www.magicianswithoutborders.com", :target=>"_blank", :title=>"Magos Sin Fronteras (Magicians Without Borders)"
    %p 
      En Colombia Conectando Sonrisas es un aliado oficial de la organización internacional: 
      %a{:target=>"_blank", :href=>"http://www.magicianswithoutborders.com"} Magos Sin Fronteras
  .allies.span6{:style=>"min-height:140px;"}
    = link_to image_tag("http://www.redsuma.org/wp-content/uploads/2013/04/LOGODEFRECOJO.jpg.jpg", :style=>"height: 185px;"), "http://recojo.net/", :target=>"_blank", :title=>"Visita RECOJO"
    %p Hacemos parte de las iniciativas sociales aliadas de la Red Colombiana de Jóvenes RECOJO.            
.row
  %h2.social-title Sitios Web y Artistas Aliados
.row
  .allies.span12
    = link_to image_tag("http://www.ligasonrisas.org/uploads/8/6/4/5/8645542/7737797_orig.png"), "http://www.pastomagic.com/blog", :target=>"_blank", :title=>"Pastomagic"
.row
  .allies.span6
    = link_to image_tag("http://www.ligasonrisas.org/uploads/8/6/4/5/8645542/9448218_orig.png", :style=>"height:190px;"), "http://www.pastomagic.com", :target=>"_blank", :title=>"Visita la página del mago German Arciniegas"
    %p El Mago Colombiano Germán Arciniegas pertenece a una nueva generación de magos, fue artista invitado al congreso internacional Intermagic 2012 en Bogotá. En 2011 fue premiado como uno de los mejores magos de su especialidad a nivel nacional.  
  .allies.span6
    = link_to image_tag("http://www.ligasonrisas.org/uploads/8/6/4/5/8645542/976455.jpg", :style=>"height:190px;"), "http://www.blackcardm.com", :target=>"_blank", :title=>"Visita la página del mago Venezolando Black Card"
    %p Mago Venezolano experto en shows de Cartomagia con Fuego & MISTERIO para Eventos, TV & Comerciales
    &nbsp

app/views/home/contact.html.haml
.contact-info
  .contact-title
    Contáctanos
  %p
    En cualquier momento nos puedes contactar para resolver dudas, inquietudes, sugerencias, felicitaciones, o cualquier otra cosa.
    Nuestro mail de contacto es 
    %a{:href=>"mailto:info@conectandosonrisas.org?Subject=Contacto Home"}info@conectandosonrisas.org 

app/views/home/donate.html.haml
%h2.social-title Existen varias formas en las cuales puedes apoyar a Conectando Sonrisas
%p.social-p 
  Explora nuestra
  %a{:href=>"#store"}
    tienda
  gracias a monomi
.donations
  .donate.box
    .donate-item
      = link_to image_tag("/pics/profile/missing.png", :title=>"Ve a nuestra tienda virtual", :height=>"75px"), "http://conectando-sonrisas.monomi.co/", :target=>"_blank"
      %p 
        Visita nuestra
        = link_to "tienda virtual", "http://conectando-sonrisas.monomi.co/", :target=>"_blank"
    .donate-item
      = link_to image_tag("http://monomi.co/static/landing/img/logo.png", :title=>"visita monomi para crear tu propia tienda en internet"), "http://monomi.co", :target=>"_blank"
      %p Visita monomi para crear tu propia tienda  
.donations
  .donate-item2
    = link_to image_tag("LigaDeLasSonrisasLogoTrans.png", :width=>"160px"), "http://ligasonrisas.org/donaciones.html", :target=>"_blank", :title=>"Dona a La Liga de las Sonrisas"
    %p Si quieres apoyar a la Fundación la Liga de las Sonrisas, que es una Entidad sin ánimo de lucro que administra este portal, lo puedes hacer por medio de transferencia o consignación en la cuenta de ahorros Bancolombia 60175063890
%a{:name=>"store"}
%iframe{:src=>"http://conectando-sonrisas.monomi.co/", :style=>"width:1000px;height:980px;margin-left:-25px;" }
        

app/views/home/event_comments.html.haml
= render :partial=>"events_comments"

app/views/home/index.html.erb
  <div id="home">
  <h1 class="title"><%= I18n.t("home.welcome") %></h1>

    <p class="home_message">
    <%= I18n.t("home.message").html_safe %>
    </p>
    <p>
    <%= I18n.t("home.now") %>
    </p>
    <p>
    <%=@facilitators%> <%= link_to I18n.t('home.facilitators'), facilitators_path %>
    </p>
    <p>
    <%=@fundations%> <%= link_to I18n.t('home.fundations'), fundations_path %>
    </p>
    <p>
    <%=@providers%> <%= link_to I18n.t('home.providers'), providers_path %>
    </p>
    <p>
    <%=@events%> <%= link_to I18n.t('home.events'), events_path %>
    </p>
    <div id="event_pics">
    <%= render :partial=>"events_photos"%>
    </div>
    <p>
    <div id="home_event_comments">
    <%= render :partial=>"events_comments"%>
    </div>    
    </p>  
    <% unless member_signed_in?  %>
      <p>
        <%= I18n.t('home.join')%> <%= link_to I18n.t("account.login"), new_member_session_path %>
      </p>
    <% end %>
</div>
<div id="twitter_msgs">
<script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 10,
  interval: 4000,
  width: 200,
  height: 250,
  theme: {
    shell: {
      background: '#ffffff',
      color: '#5bb548'
    },
    tweets: {
      background: '#ffffff',
      color: '#827d82',
      links: '#5bb548'
    }
  },
  features: {
    scrollbar: false,
    loop: true,
    live: true,
    hashtags: true,
    timestamp: true,
    avatars: true,
    behavior: 'default'
  }
}).render().setUser('consonrisas').start();
</script>
<style type="text/css">
#twitter_msgs
{
border-style:solid;
border-color:#5bb548;
border-width:1px;
position:absolute;
left:850px;
top:250px;
}
</style>
</div>
 <%= javascript_include_tag "jquery.smoothDivScroll-1.1-min" %>
 <%= javascript_include_tag "ui.home" %>  

app/views/home/landing.html.haml
= render :partial=>"landing_slider"

app/views/home/landing_fundations.html.haml
.landing-background
  .landing-logo
    = image_tag "/logos/LogoConUrl.png"
  .landing-header.fundation
    =image_tag "/images/FundacionesTransparenteMedio.png"
    .text
      Si trabajas en un 
      %b Proyecto Social
      que tiene necesidades, regístrate en Conectando Sonrisas.
      %br
      %li
        Aquí encontrarás facilitadores que te pueden ayudar a suplirlas. 
      %br
      Si en tu
      %b Proyecto Social
      haces
      %b Eventos
      y quieres que estén llenos de sonrisas, regístrate en Conectando Sonrisas.
      %br
      %li
        En esta comunidad virtual también podrás encontrar entretenimiento para estos.
  .steps
    .step.step1
      %p.number-title
        1
      %p.step-title
        Datos de Registro
      = render "registrations/new_landing"
    .step.step2
      %p.number-title
        2  
      %p.step-title
        Datos Proyecto Social
      .step2-form
        = render "fundations/form_landing"
    .step.step3
      %p.number-title
        3  
      #step3-form          
        %p.step-title
          Crea una necesidad      
        = form_for :project_need do |f|
          .field.need_field
            = f.label I18n.t('name')
            %br/
            = f.text_field :name, :maxlength=>"20", :class=>"input-landing"
          .field.need_field
            = f.label I18n.t('recurrence')
            %br/
            = f.text_field :recurrence, :maxlength=>"20", :class=>"input-landing"
          .field.need_field
            = f.label I18n.t('category')
            %br/
            = select_tag("project_need[need_category_id]", options_for_select(NeedCategory.all.map {|category| [need_category_name(category), category.id]}, "1"), :id=>"need_cat_select", :include_blank => I18n.t('other'))
          #other_need_category.field{:style => "display:none; clear:both;"}
            = f.label I18n.t('category')
            \:
            \#{f.text_field :category, :maxlength=>"20", :class=>"input-landing"}
          .need_form_actions
            = f.submit :value=>"Crea una necesidad", :class=>"need_button add_need", :fundation_id=>"#{@fundation.id}"
      .done-container{:style=>"display:none"}  
        %a{:href=>"/soyproyecto", :class=>"done-button"} LISTO
= image_tag "/images/loaders/fundations-loader-big.gif", :class=>"big-loader", :style=>"display:none"
= javascript_include_tag "landing/landingFundations"

app/views/home/results2012.html.haml
.row
  %h1 Resultados del 2012

app/views/home/touch.html.erb
<script type="text/javascript" src="http://cdn.onswipe.com/synapse/on.js?usr=consonrisas" id="onswipe_synapse"></script>