config/routes.rb
Consonrisas::Application.routes.draw do
  
  resources :contests

  get "/corteo" => "contests#new", :as => :corteo

  resources :need_categories

  get "need/create"

  get "need/destroy"
  
  get "project_need/create"

  get "project_need/destroy"

  resources :news

  get "search/find"

  match '/auth/facebook/logout' => 'application#facebook_logout', :as => :facebook_logout
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  
  resources :authentications

  devise_for :members, :controllers => {:registrations => 'registrations'}
  get "admin/index"
  match 'admin/', :controller => 'admin', :action => 'index'
  match 'admin/db/:table_name.:format', :controller => 'admin', :action => 'get_table_data'  
  match 'admin/db/:table_name/:id', :controller => 'admin', :action => 'update_table_data', :conditions => {:method => :put }  
  match 'admin/db/:table_name', :controller => 'admin', :action => 'create_table_data', :conditions => {:method => :post}
  match 'admin/db/delete/:table_name/:id', :controller => 'admin', :action => 'delete_table_data', :conditions => {:method => :delete }    
  get "admin/members_to_csv" =>"admin#members_to_csv"
  get "admin/fundation_admins_to_csv" =>"admin#fundation_admins_to_csv"  
  get "admin/events_to_csv" =>"admin#events_to_csv"  
  get "admin/fundations_to_csv" =>"admin#fundations_to_csv"  

  
  get "admin/dj_all", :as => :dj_all

  get "admin/dj_show/:id"=> "admin#dj_show"

  get "admin/dj_destroy/:id" => "admin#dj_destroy"
  
  get "admin/workers" => "admin#see_workers"
  
  post "admin/set_workers" => "admin#set_workers"
  

  get "events/gallery"
  
  get "events/all_events"

  post "events/add_facilitator"
  post "events/add_facilitators"  
  post "events/add_fundation"
  post "events/add_fundations"  
  post "events/add_provider"
  post "events/add_providers"  
  post "events/add_show"  
  
  post "events/remove_facilitator"
  post "events/remove_fundation"
  post "events/remove_provider"  
  
  post "fundations/add_follower"
  post "fundations/remove_follower"
  post "fundations/send_msg_to_admins"    
  
  post "providers/add_follower"
  post "providers/remove_follower"
  post "providers/send_msg_to_admins"  
  
  post "facilitators/add_follower"
  post "facilitators/remove_follower"
  post "facilitators/send_msg"
  
  post "fundations/ask_admin"
  post "providers/ask_admin"  
  post "events/ask_admin"  
  
  post "members/respond_fundation_admin"
  post "members/respond_provider_admin"
  post "members/respond_event_admin"    
  match "members/edit_settings"  => "members#edit_settings", :as => :edit_settings
  post "members/delete_alert"      
  get "members/:id/get_fundations" => "members#get_fundations" 
  post "members/check_email" => "members#check_email"
  post "fundations/check_name" => "fundations#check_name"

  root :to => "home#new_index"
  
  get "/info" =>"home#info"

  get "home/new_index"
  get "home/event_comments"
  get "/social" => "home#social"
  get "/mobile" => "home#mobile"
  post "home/feedback"
  
  post "/cleanInitialSession" => "members#cleanInitialSession"
  
  get 'photos/poll'
  

  
  match 'needs/complete/:id' => 'needs#complete'

  get "/facilitators/list" => "facilitators#list"  
 

  
  resources :roles

  resources :members do
    post "update_facebook_id"
    put "change_pic"  
    get "my_invites"
    get "my_msgs"
    post "seen_msgs"
    post "seen_invites"
  end
  post "/members_register" => "members#register"
  post "/accept_invite/:event_id/:role_id" => "members#accept_invite"
  post "/reject_invite/:event_id/:role_id" => "members#reject_invite"  

  resources :populations

  get "/landing" => "home#landing"
  match "project_needs/all_needs", :as => "all_needs"
  match "project_needs/all_needs_landing", :as => "all_needs_landing"  
  get "/soyproyecto" => "home#landing_fundations"
  get "/soyfacilitador" => "home#landing_facilitators"
  get "/soyproveedor" => "home#landing_providers"    
  get "/legal" => "home#legal"

  localized(['es', 'en'], :verbose => true) do
    get "/contact" => "home#contact", :as => :contact
    get "/touch" =>"home#touch", :as => :touch
    get "/donate" =>"home#donate", :as => :donate
    get "/dona" =>"home#donate", :as => :donate
    get "/allies" =>"home#allies",  :as => :allies
    get "/services" => "home#services", :as => :services
    
    resources :events do
      get 'show_gallery'
      resources :photos
      resources :comments
      resources :needs do
          post "complete"
      end
    end  
    resources :facilitators
    resources :providers do
      get "get_pic"
      put "change_pic"
      resources :shows
      resources :contact_informations
    end
    resources :fundations do
      put "change_pic"    
      get "needs"
      resources :contact_informations
      resources :project_needs do
        get 'need'
        post 'help'
      end
         
    end
  end

end

app/models/population.rb
class Population < ActiveRecord::Base
  has_many :shows
  has_and_belongs_to_many :fundations, :join_table => :fundation_populations, :uniq => true
  has_and_belongs_to_many :facilitators, :join_table => :facilitator_populations, :uniq => true
end

app/controllers/populations_controller.rb
class PopulationsController < ApplicationController
  before_filter :authenticate_member!, :except => [:index, :show]
  # GET /populations
  # GET /populations.xml
  def index
    @populations = Population.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @populations }
    end
  end

  # GET /populations/1
  # GET /populations/1.xml
  def show
    @population = Population.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @population }
    end
  end

  # GET /populations/new
  # GET /populations/new.xml
  def new
    @population = Population.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @population }
    end
  end

  # GET /populations/1/edit
  def edit
    @population = Population.find(params[:id])
  end

  # POST /populations
  # POST /populations.xml
  def create
    @population = Population.new(params[:population])

    respond_to do |format|
      if @population.save
        format.html { redirect_to(@population, :notice => 'Population was successfully created.') }
        format.xml  { render :xml => @population, :status => :created, :location => @population }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @population.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /populations/1
  # PUT /populations/1.xml
  def update
    @population = Population.find(params[:id])

    respond_to do |format|
      if @population.update_attributes(params[:population])
        format.html { redirect_to(@population, :notice => 'Population was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @population.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /populations/1
  # DELETE /populations/1.xml
  def destroy
    @population = Population.find(params[:id])
    @population.destroy

    respond_to do |format|
      format.html { redirect_to(populations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/populations_helper.rb
module PopulationsHelper
  def population_name(id)
    name = ""
    p = Population.find(id)
    name = p.name_es if "#{I18n.locale}" == "es"
    name = p.name_en if "#{I18n.locale}" == "en"
    name
  end
  
end

app/views/populations/_form.html.erb
<%= form_for(@population) do |f| %>
  <% if @population.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@population.errors.count, "error") %> prohibited this population from being saved:</h2>

      <ul>
      <% @population.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :age_min %><br />
    <%= f.text_field :age_min %>
  </div>
  <div class="field">
    <%= f.label :age_max %><br />
    <%= f.text_field :age_max %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/populations/edit.html.erb
<h1>Editing population</h1>

<%= render 'form' %>

<%= link_to 'Show', @population %> |
<%= link_to 'Back', populations_path %>

app/views/populations/index.html.erb
<h1>Listing populations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Age min</th>
    <th>Age max</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @populations.each do |population| %>
  <tr>
    <td><%= population.name %></td>
    <td><%= population.description %></td>
    <td><%= population.age_min %></td>
    <td><%= population.age_max %></td>
    <td><%= link_to 'Show', population %></td>
    <td><%= link_to 'Edit', edit_population_path(population) %></td>
    <td><%= link_to 'Destroy', population, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Population', new_population_path %>

app/views/populations/new.html.erb
<h1>New population</h1>

<%= render 'form' %>

<%= link_to 'Back', populations_path %>

app/views/populations/show.html.erb
<p>
  <b>Name:</b>
  <%= @population.name %>
</p>

<p>
  <b>Description:</b>
  <%= @population.description %>
</p>

<p>
  <b>Age min:</b>
  <%= @population.age_min %>
</p>

<p>
  <b>Age max:</b>
  <%= @population.age_max %>
</p>


<%= link_to 'Edit', edit_population_path(@population) %> |
<%= link_to 'Back', populations_path %>